= Draw.io Desktop Headless docker image

image:https://img.shields.io/docker/v/rlespinasse/drawio-desktop-headless[Docker Version,link=https://hub.docker.com/r/rlespinasse/drawio-desktop-headless]
image:https://img.shields.io/docker/pulls/rlespinasse/drawio-desktop-headless[Docker Pull,link=https://hub.docker.com/r/rlespinasse/drawio-desktop-headless]
image:https://github.com/rlespinasse/docker-drawio-desktop-headless/workflows/Build/badge.svg[Build]

Dockerized headless version of https://github.com/jgraph/drawio-desktop[Draw.io Desktop '21.6.5']

== What is does

Draw.io Desktop expose a command-line client to allow us to create, check or export diagrams.

Since Draw.io Desktop is an GUI application, we need an GUI environment to run it.
And this prevent us to use it for automation in non-GUI environment such as CI tools.

This docker image enable us to run the command-line client in a headless mode by using a configurable **X** server.

Other minor addition are available

* Add timeout capability since the application can hang sometimes (due to user action needed in GUI mode)
* Clear the output log from Electron Security Warning
* Disable auto-update functionality to avoid unneccessary log
* Multiple fonts from
** https://packages.debian.org/bullseye/fonts-liberation[fonts-liberation]
** https://packages.debian.org/bullseye/fonts-arphic-ukai[fonts-arphic-ukai]
** https://packages.debian.org/bullseye/fonts-arphic-uming[fonts-arphic-uming]
** https://packages.debian.org/bullseye/fonts-noto[fonts-noto]
** https://packages.debian.org/bullseye/fonts-noto-cjk[fonts-noto-cjk]
** https://packages.debian.org/bullseye/fonts-ipafont-mincho[fonts-ipafont-mincho]
** https://packages.debian.org/bullseye/fonts-ipafont-gothic[fonts-ipafont-gothic]
** https://packages.debian.org/bullseye/fonts-unfonts-core[fonts-unfonts-core]

NOTE: Want a new font package, modify the `Dockerfile` to install the missing package.

== Running

[source,bash]
----
docker run -it -w /data -v $(pwd):/data rlespinasse/drawio-desktop-headless
----

=== Configuration

[cols="2a,3a,1a",options="header"]
|===

| Environment Variable
| Description
| Default Value

| **DRAWIO_DESKTOP_COMMAND_TIMEOUT**
| To prevent Draw.io Desktop process to hang indefinitely.

The value is a floating point number with an optional suffix: 's'
for seconds (the default), 'm' for minutes, 'h' for hours or 'd'
for days.  A duration of 0 disables the associated timeout.
| `10s`

| **XVFB_DISPLAY**
| Screen Display setup for XVFB
| `:42`

| **XVFB_OPTIONS**
| Options for Xvfb
|

| **ELECTRON_DISABLE_SECURITY_WARNINGS**
| Avoid printing https://github.com/electron/electron/blob/master/docs/tutorial/security.md#electron-security-warnings[electron warning]
| `true`

| **DRAWIO_DISABLE_UPDATE**
| Disable auto-update of Draw.io Desktop
| `true`

|===

== Use as docker base image

This docker image can be used as base image to build a higher-level tool upon it.

In addition of running configuration, you have access to

- `DRAWIO_DESKTOP_EXECUTABLE_PATH` to have access to the executable path of Draw.io Desktop.
- `DRAWIO_DESKTOP_RUNNER_COMMAND_LINE` to run your script instead of the default one.

=== Used by

* Docker image https://github.com/rlespinasse/drawio-export[**rlespinasse/drawio-export**] which enhance export capabilities of the **Draw.io Desktop Headless** docker image,
** And GitHub Action https://github.com/rlespinasse/drawio-export-action[**rlespinasse/drawio-export-action**] which is build on top of **drawio-export** docker image.

== Thanks to

Thanks for the community about https://github.com/jgraph/drawio-desktop/issues/127[the work around docker-image based of Draw.io Desktop].

== Contributing

Pull requests are welcome.
For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.
