name: Dependencies Auto-Update
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight (UTC)
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    concurrency:
      group: autoupdate-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - run: make autoupdate
        shell: bash
      - uses: peter-evans/create-pull-request@v5
        with:
          title: "feat: bump dependencies"
          branch: dependencies-autoupdate
          reviewers: rlespinasse
