---
name: Build And Release

on:
  pull_request:
  push:
    branches:
      - v1.x

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: build-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - uses: rlespinasse/github-slug-action@v5

      - uses: taiki-e/install-action@just

      - name: Build docker image
        run: just build
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Setup CI for test
        run: just test-ci-setup
        shell: bash

      - name: Test docker image
        run: just test-ci
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

      - name: Test docker image // Store output logs
        uses: actions/upload-artifact@v5
        with:
          name: test-docker-image-logs
          path: "tests/output/*.log"
        if: ${{ always() }}

      - name: Test docker image // Store output files
        uses: actions/upload-artifact@v5
        with:
          name: test-docker-image-files
          path: |
            tests/data
            !tests/data/*.drawio
            !tests/data/*/*.drawio
        if: ${{ always() }}

  build-multiarch:
    runs-on: ubuntu-latest

    concurrency:
      group: build-multiarch-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - uses: rlespinasse/github-slug-action@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64,arm"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: taiki-e/install-action@just

      - name: Build docker image
        run: just build-multiarch
        shell: bash
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      id-token: write
      packages: write

    needs:
      - build
      - build-multiarch

    concurrency:
      group: release-${{ github.ref }}-${{ github.event_name }}

    steps:
      - uses: actions/checkout@v5

      - name: Release this docker image
        uses: rlespinasse/release-that@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
