name: Build And Release
on:
  pull_request:
  push:
    branches:
      - v1.x
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v4
      - name: Build docker image
        run: make build
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}
      - name: Test docker image
        run: |
          make setup-test-on-ci
          make test
        env:
          DOCKER_IMAGE: ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

  release:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: release-${{ github.ref }}-${{ github.event_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Release this docker image
        uses: rlespinasse/release-that@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
