name: Publish to Registry
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: rlespinasse/drawio-desktop-headless
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.GITHUB_REF_SLUG }}"
