---
name: Update Docker Hub information

on:
  release:
    types: [published]
  push:
    branches:
      - v1.x
    paths:
      - DOCKER.md
      - .github/workflows/update-dockerhub.yaml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync information on Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: rlespinasse
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rlespinasse/drawio-desktop-headless
          readme-filepath: ./DOCKER.md
